language: csharp
solution: DnDGen.CreatureGen.sln
mono: none
dotnet: 3.1

script:
  - dotnet build DnDGen.CreatureGen.sln -c Release
    && dotnet test ./DnDGen.CreatureGen.Tests.Unit/DnDGen.CreatureGen.Tests.Unit.csproj -v normal
    && dotnet test ./DnDGen.CreatureGen.Tests.Integration.IoC/DnDGen.CreatureGen.Tests.Integration.IoC.csproj -v normal
    && dotnet test ./DnDGen.CreatureGen.Tests.Integration.Tables/DnDGen.CreatureGen.Tests.Integration.Tables.csproj -v normal
    && dotnet test ./DnDGen.CreatureGen.Tests.Integration/DnDGen.CreatureGen.Tests.Integration.csproj -v normal
    && dotnet test ./DnDGen.CreatureGen.Tests.Integration.Stress/DnDGen.CreatureGen.Tests.Integration.Stress.csproj -v normal -c Stress
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master
matrix:
  fast_finish: true
