language: csharp
mono: latest
solution: CreatureGen.sln
install:
  - curl -O https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono ./nuget.exe restore CreatureGen.sln
  - mono ./nuget.exe install NUnit.Runners -OutputDirectory testrunner
script:
  - msbuild CreatureGen.sln /p:TargetFrameworkVersion="v4.5" /p:Configuration=Stress
  - set -e
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./CreatureGen.Tests.Unit/bin/Stress/CreatureGen.Tests.Unit.dll
  - set -e
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./CreatureGen.Tests.Integration.IoC/bin/Stress/CreatureGen.Tests.Integration.IoC.dll
  - set -e
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./CreatureGen.Tests.Integration.Tables/bin/Stress/CreatureGen.Tests.Integration.Tables.dll
  - set -e
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./CreatureGen.Tests.Integration/bin/Stress/CreatureGen.Tests.Integration.dll
  - set -e
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./CreatureGen.Tests.Integration.Stress/bin/Stress/CreatureGen.Tests.Integration.Stress.dll
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master
matrix:
  fast_finish: true
